/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;

/**
 *
 * @author edodomi
 */
public class SelectFileView extends javax.swing.JFrame {

    /**
     * Creates new form Information
     */
    public SelectFileView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        chooseFile_1 = new javax.swing.JButton();
        keyRadio = new javax.swing.JRadioButton();
        keyButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        readFileText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        saveFileText = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        keyPath = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        choseFile_2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ok.setText("Ok");

        cancel.setText("Cancel");

        chooseFile_1.setText("Choose File");

        keyRadio.setText("Generate key dynamically");
        keyRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyRadioActionPerformed(evt);
            }
        });

        keyButton.setText("Choose File");

        readFileText.setColumns(20);
        readFileText.setRows(5);
        jScrollPane1.setViewportView(readFileText);

        saveFileText.setColumns(20);
        saveFileText.setRows(5);
        jScrollPane2.setViewportView(saveFileText);

        keyPath.setColumns(20);
        keyPath.setRows(5);
        jScrollPane3.setViewportView(keyPath);

        jLabel4.setText("Read file");

        jLabel5.setText("Save file");

        jLabel6.setText("File with Key");

        choseFile_2.setText("Choose File");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(choseFile_2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chooseFile_1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(keyRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(keyButton)
                            .addComponent(ok))))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancel, keyButton, ok});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2, jScrollPane3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(chooseFile_1)))
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(choseFile_2)
                        .addGap(9, 9, 9)))
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(keyButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(ok)
                    .addComponent(keyRadio))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {chooseFile_1, keyButton});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane2, jScrollPane3});

        setSize(new java.awt.Dimension(661, 375));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void keyRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keyRadioActionPerformed

    public void addKeyRadio(ActionListener listener){
        keyRadio.addActionListener(listener);
    }
     
    public void addKeyButton(ActionListener listener){
        keyButton.addActionListener(listener);
    }

    public void addChooseFile_1_Button(ActionListener listener){
       chooseFile_1.addActionListener(listener);
    }
       
    public void addChooseFile_2_Button(ActionListener listener){
        choseFile_2.addActionListener(listener);
    }
       
    public void addCancelButton(ActionListener listener){
        cancel.addActionListener(listener);
    }
       
    public void addOkButton(ActionListener listener){
        ok.addActionListener(listener);
    }
      
    public String getReadFileText(){
        return readFileText.getText();
    }
      
    public String getSaveFileText(){
        return saveFileText.getText();
    }
  
    public void setSaveFileText(String text){
        saveFileText.setText(text);
    }   
  
    public void setReadFileText(String text){
        readFileText.setText(text);
    }
     
    public Object[] getStateKeyRadio(){
        return keyRadio.getSelectedObjects();
     }
     
    public void setKeyTextEnabled(){
        keyPath.setEnabled(true);
        keyButton.setEnabled(true);
     }
     
    public void setKeyTextDisabled(){
        keyPath.setEnabled(false);
        keyButton.setEnabled(false);
     }
     
    public void setKeyPath(String text){
        keyPath.setText(text);
     }
     
    public String getKeyPath(){
        return keyPath.getText();
     }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton chooseFile_1;
    private javax.swing.JButton choseFile_2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton keyButton;
    private javax.swing.JTextArea keyPath;
    private javax.swing.JRadioButton keyRadio;
    private javax.swing.JButton ok;
    private javax.swing.JTextArea readFileText;
    private javax.swing.JTextArea saveFileText;
    // End of variables declaration//GEN-END:variables
}
