/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kryptografia_zadanie1_mvc;

import java.awt.event.ActionListener;

/**
 *
 * @author edodomi
 */
public class SelectFileView extends javax.swing.JFrame {

    /**
     * Creates new form Information
     */
    public SelectFileView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        chooseFile_1 = new javax.swing.JButton();
        choseFile_2 = new javax.swing.JButton();
        readFileText = new javax.swing.JTextField();
        saveFileText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        keyRadio = new javax.swing.JRadioButton();
        keyPath = new javax.swing.JTextField();
        keyButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ok.setText("Ok");

        cancel.setText("Cancel");

        chooseFile_1.setText("Choose File");

        choseFile_2.setText("Choose File");

        readFileText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readFileTextActionPerformed(evt);
            }
        });

        jLabel1.setText("Read File");

        jLabel2.setText("Save File");

        keyRadio.setText("Generate key dynamically");
        keyRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyRadioActionPerformed(evt);
            }
        });

        keyPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyPathActionPerformed(evt);
            }
        });

        keyButton.setText("Choose File");

        jLabel3.setText("Key File");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(readFileText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooseFile_1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(saveFileText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(choseFile_2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(keyPath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(keyButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(keyRadio, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ok)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancel, choseFile_2, keyButton, ok});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(readFileText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseFile_1))
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choseFile_2)
                    .addComponent(saveFileText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keyPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keyButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok)
                    .addComponent(cancel)
                    .addComponent(keyRadio))
                .addGap(28, 28, 28))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {chooseFile_1, choseFile_2, keyButton, keyPath, readFileText, saveFileText});

        setSize(new java.awt.Dimension(628, 348));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void keyPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keyPathActionPerformed

    private void keyRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keyRadioActionPerformed

    private void readFileTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readFileTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readFileTextActionPerformed

    public void addKeyRadio(ActionListener listener){
        keyRadio.addActionListener(listener);
    }
     
    public void addKeyButton(ActionListener listener){
        keyButton.addActionListener(listener);
    }

    public void addChooseFile_1_Button(ActionListener listener){
       chooseFile_1.addActionListener(listener);
    }
       
    public void addChooseFile_2_Button(ActionListener listener){
        choseFile_2.addActionListener(listener);
    }
       
    public void addCancelButton(ActionListener listener){
        cancel.addActionListener(listener);
    }
       
    public void addOkButton(ActionListener listener){
        ok.addActionListener(listener);
    }
      
    public String getReadFileText(){
        return readFileText.getText();
    }
      
    public String getSaveFileText(){
        return saveFileText.getText();
    }
  
    public void setSaveFileText(String text){
        saveFileText.setText(text);
    }   
  
    public void setReadFileText(String text){
        readFileText.setText(text);
    }
     
    public Object[] getStateKeyRadio(){
        return keyRadio.getSelectedObjects();
     }
     
    public void setKeyTextEnabled(){
        keyPath.setEnabled(true);
        keyButton.setEnabled(true);
     }
     
    public void setKeyTextDisabled(){
        keyPath.setEnabled(false);
        keyButton.setEnabled(false);
     }
     
    public void setKeyPath(String text){
        keyPath.setText(text);
     }
     
    public String getKeyPath(){
        return keyPath.getText();
     }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton chooseFile_1;
    private javax.swing.JButton choseFile_2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton keyButton;
    private javax.swing.JTextField keyPath;
    private javax.swing.JRadioButton keyRadio;
    private javax.swing.JButton ok;
    private javax.swing.JTextField readFileText;
    private javax.swing.JTextField saveFileText;
    // End of variables declaration//GEN-END:variables
}
